// src/data/courses.js
export const courses = [
  { title: "Prompt Crafting", tech: "AI", sections: 46, progress: 45, locked: false },
  { title: "AI Ethics", tech: "AI", sections: 18, progress: 100, locked: false },
  { title: "AI Fundamentals", tech: "AI", sections: 32, progress: 70, locked: false },
  { title: "AI Automation", tech: "AI", sections: 24, progress: 0, locked: true },
  { title: "Generative AI", tech: "AI", sections: 36, progress: 0, locked: true },
  { title: "Machine Learning", tech: "ML", sections: 60, progress: 35, locked: false },
  { title: "Supervised Learning", tech: "ML", sections: 22, progress: 0, locked: false },
  { title: "Unsupervised Learning", tech: "ML", sections: 26, progress: 0, locked: true },
  { title: "Reinforcement Learning", tech: "ML", sections: 34, progress: 0, locked: true },
  { title: "ML Mathematics", tech: "ML", sections: 40, progress: 0, locked: true },
  { title: "HTML & CSS", tech: "Web", sections: 40, progress: 100, locked: false },
  { title: "JavaScript Mastery", tech: "Web", sections: 55, progress: 60, locked: false },
  { title: "Web Accessibility", tech: "Web", sections: 20, progress: 0, locked: false },
  { title: "Web Performance", tech: "Web", sections: 22, progress: 0, locked: true },
  { title: "SEO for Developers", tech: "Web", sections: 18, progress: 0, locked: true },
  { title: "Frontend Fundamentals", tech: "Frontend", sections: 32, progress: 20, locked: false },
  { title: "React Fundamentals", tech: "Frontend", sections: 48, progress: 25, locked: false },
  { title: "Next.js Mastery", tech: "Frontend", sections: 42, progress: 0, locked: true },
  { title: "State Management", tech: "Frontend", sections: 28, progress: 0, locked: true },
  { title: "Frontend Testing", tech: "Frontend", sections: 24, progress: 0, locked: true },
  { title: "UI/UX Fundamentals", tech: "UIUX", sections: 30, progress: 40, locked: false },
  { title: "Design Thinking", tech: "UIUX", sections: 24, progress: 0, locked: false },
  { title: "User Research", tech: "UIUX", sections: 20, progress: 0, locked: false },
  { title: "Figma for Designers", tech: "UIUX", sections: 36, progress: 0, locked: true },
  { title: "Design Systems", tech: "UIUX", sections: 26, progress: 0, locked: true },
  { title: "Backend Fundamentals", tech: "Backend", sections: 28, progress: 0, locked: true },
  { title: "Node.js", tech: "Backend", sections: 38, progress: 0, locked: true },
  { title: "Databases", tech: "Backend", sections: 30, progress: 0, locked: true },
  { title: "REST APIs", tech: "Backend", sections: 26, progress: 0, locked: true },
  { title: "GraphQL APIs", tech: "Backend", sections: 24, progress: 0, locked: true },
  { title: "Mobile App Basics", tech: "Mobile", sections: 28, progress: 0, locked: true },
  { title: "React Native", tech: "Mobile", sections: 44, progress: 0, locked: true },
  { title: "Flutter Fundamentals", tech: "Mobile", sections: 40, progress: 0, locked: true },
  { title: "Mobile UI Design", tech: "Mobile", sections: 22, progress: 0, locked: true },
  { title: "Mobile Security", tech: "Mobile", sections: 18, progress: 0, locked: true },
  { title: "Data Science Fundamentals", tech: "Data Science", sections: 30, progress: 0, locked: true },
  { title: "Python for Data Science", tech: "Data Science", sections: 35, progress: 0, locked: true },
  { title: "Statistics & Probability", tech: "Data Science", sections: 28, progress: 0, locked: true },
  { title: "Machine Learning Basics", tech: "Data Science", sections: 40, progress: 0, locked: true },
  { title: "Data Visualization", tech: "Data Science", sections: 25, progress: 0, locked: true },
  { title: "Big Data & Analytics", tech: "Data Science", sections: 32, progress: 0, locked: true },
];
